### ISSUE TITLE
corrupt output files

### ISSUE THREAD

**Issue by ameisner** [legacysurvey/legacyzpts#29]
we should either implement a safety mechanism guarding against this like we have in legacypipe, or else put in place an after-burner validation script to loop over the files and make sure none are corrupted

**Comment by dstndstn** [comment]
Agreed.  In other places, I first write to a temp file, then rename it, so that if the file exists, it has the right contents.  But the zeropoints code produces a bunch of files (the subject of another ticket!), so we should decide which file should be written last, and then the existence of that file can be used as a proxy for determining (on re-run) whether we're already done or not.

**Comment by dstndstn** [comment]
done in ceaa0dd
