### ISSUE TITLE
PROCDATE vs. PLPROCID

### ISSUE THREAD

**Issue by schlafly** [legacysurvey/legacyzpts#47]
We currently identify images as having a common EXPNUM + PLVER + PROCDATE.  PROCDATE is not ideal for this purpose because ooi/ood/oow images have different procdates, according to when they happened to be processed (though the dates are different only by tens of seconds).  If we migrate from PROCDATE to PLPROCID, we will eliminate this problem.

**Comment by djschlegel** [comment]
If we make this switch, we need to pay attention to the early MOSAIC data that has EXPNUM either does not exist in the file header, or exists but is unpopulated.  In the cases of missing EXPNUM, the legacypipe pipeline invents an exposure number from the OBSID keyword.  But in the cases of EXPNUM existing and not being populated, the behavior depends upon the FITS reader being used.

**Comment by schlafly** [comment]
The key here is to use legacypipe's get_expnum(...) ~consistently.  I verified for my current code that I always generate the same expnum as legacypipe, so that's good.  As you point out, my code had failed previously when EXPNUM existed in the header but was not populated.  For these cases, we also need to invent an EXPNUM from the header.

**Comment by moustakas** [comment]
One consequence of this change is that the calibs we're generating ~now won't be useful for DR9 since we're not recording the `PLPROCID` metadata.  In detail, we've only completed 18271/mosaic, 6687/90prime, and 5515/decam calibs (the decam calibs are all in the dr8 test regions, while the mosaic and 90prime calibs were a subset of the `v1` list of input images).

Shouldn't we just redo these before launching DR8 proper (but not before dr8b is done)?

**Comment by moustakas** [comment]
Done in #50.
